"""
Static Knowledge Base - Free Alternative to OpenSearch

AUTO-GENERATED by scripts/sync_faq.py from shared/faq-config.json
Do NOT edit manually — edit shared/faq-config.json and run: python scripts/sync_faq.py
"""

BRAND_INFO = {
    "name": "WECARE.DIGITAL",
    "website": "https://wecare.digital",
    "store": "https://store.wecare.digital",
    "email": "one@wecare.digital",
    "phone": "+91 9330994400",
    "whatsapp": "+91 9330994400",
    "description": "Multi-channel messaging and e-commerce platform"
}

FAQ_DATABASE = [
    {"keywords": ["hours", "timing", "open", "close", "available", "when", "time"], "question": "What are your business hours?", "answer": "We are available 24/7 for online orders and support. For urgent assistance, call us at +91 9330994400 or email one@wecare.digital."},
    {"keywords": ["contact", "reach", "call", "email", "phone", "support", "help"], "question": "How can I contact you?", "answer": "You can reach us via:\n• Phone/WhatsApp: +91 9330994400\n• Email: one@wecare.digital\n• Website: https://wecare.digital"},
    {"keywords": ["order", "buy", "purchase", "shop", "product", "cart"], "question": "How do I place an order?", "answer": "Visit our store at https://store.wecare.digital to browse products and place orders. You can also order via WhatsApp by sending us a message at +91 9330994400."},
    {"keywords": ["payment", "pay", "price", "cost", "fee", "charge", "upi", "card"], "question": "What payment methods do you accept?", "answer": "We accept:\n• UPI (Google Pay, PhonePe, Paytm)\n• Credit/Debit Cards\n• Net Banking\n• Razorpay Payment Gateway\n\nA 2.2% convenience fee + 18% GST applies to all payments."},
    {"keywords": ["delivery", "shipping", "ship", "courier", "dispatch", "send"], "question": "What are your delivery options?", "answer": "We offer standard shipping across India. Delivery time varies by location (typically 3-7 business days). Track your order status in the My Orders section."},
    {"keywords": ["return", "refund", "cancel", "exchange", "money back"], "question": "What is your return policy?", "answer": "Returns are accepted within 7 days of delivery for eligible items. Contact us at one@wecare.digital with your order number to initiate a return. Refunds are processed within 5-7 business days."},
    {"keywords": ["track", "status", "where", "order status", "tracking"], "question": "How do I track my order?", "answer": "Log in to your account at https://store.wecare.digital and visit the My Orders page to track your order status in real-time."},
    {"keywords": ["whatsapp", "message", "chat", "wa", "messenger"], "question": "Can I order via WhatsApp?", "answer": "Yes! Send us a message on WhatsApp at +91 9330994400. Our AI assistant will help you browse products and place orders directly through chat."},
    {"keywords": ["invoice", "bill", "receipt", "gst", "tax"], "question": "How do I get my invoice?", "answer": "Your invoice is automatically generated after payment and sent to your registered email. You can also download it from the My Orders section or request it via email."},
    {"keywords": ["account", "login", "register", "signup", "password", "profile"], "question": "How do I create an account?", "answer": "Visit https://store.wecare.digital and click on the account icon to register. You can also place orders as a guest without creating an account."},
    {"keywords": ["convenience fee", "extra charge", "additional fee", "why charge"], "question": "What is the convenience fee?", "answer": "A 2.2% convenience fee is charged on the cart total, plus 18% GST on that fee. This covers payment gateway and processing costs. Total fee = (Cart × 2.2%) × 1.18"},
    {"keywords": ["bulk", "wholesale", "large order", "quantity", "discount"], "question": "Do you offer bulk order discounts?", "answer": "Yes! For bulk orders, please contact us at one@wecare.digital or call +91 9330994400. We offer special pricing for large quantities."},
    {"keywords": ["submit", "request", "service", "help", "issue", "problem", "complaint"], "question": "How do I submit a request?", "answer": "Submit a service request via WhatsApp (select 'Submit Request' from the menu) or via the web dashboard at Service → Submit Request. Select your order first, then describe your issue."},
    {"keywords": ["track", "request", "status", "check", "progress", "follow"], "question": "How can I track my request?", "answer": "Track your request by Order ID via WhatsApp ('Track Request' menu) or the web dashboard (Service → Track Request). View all requests, status timeline, payments, and documents for that order."},
    {"keywords": ["amend", "change", "modify", "update", "edit", "correct"], "question": "How do I request an amendment?", "answer": "Amend an existing request via WhatsApp ('Amend Request' menu) or web (Service → Amend Request). Select your order, choose the request to amend, describe changes, and submit."},
    {"keywords": ["rx", "slot", "prescription", "pharmacy", "medicine", "medical"], "question": "How do I book or reschedule an RX slot?", "answer": "Book an RX slot via WhatsApp ('RX Slot' menu) or web (Booking → RX Slots). Choose date, time, and provider. Reschedule or cancel from the same page."},
    {"keywords": ["document", "upload", "docs", "drop", "file", "prescription", "proof"], "question": "How do I upload supporting documents?", "answer": "Send documents via WhatsApp to +91 9330994400 (auto-ingested) or use Drop Docs on the web dashboard. Documents are reviewed by our team with status tracking."},
    {"keywords": ["enterprise", "business", "corporate", "b2b", "company", "technical"], "question": "How do I get enterprise support?", "answer": "For enterprise support, select 'Enterprise Assist' on WhatsApp or go to Enterprise in the dashboard. Provide company details, describe the issue, and set priority."},
    {"keywords": ["appointment", "book", "schedule", "consultation", "visit", "meeting"], "question": "How do I book an appointment?", "answer": "Book via WhatsApp ('Schedule Appointment' menu) or web (Booking → Appointments). Choose type, date/time, and location. Confirmations and reminders sent via WhatsApp."},
    {"keywords": ["review", "feedback", "rating", "rate", "experience", "star"], "question": "How do I leave a review?", "answer": "Leave a review via WhatsApp ('Leave Review' menu) or the Reviews section on the web dashboard. Rate 1-5 stars and add comments. Reviews are moderated before publishing."},
    {"keywords": ["app", "mobile", "android", "ios", "download", "install"], "question": "Is there a mobile app?", "answer": "Yes! WECARE.DIGITAL is available as a PWA. Visit wecare.digital on mobile and tap 'Add to Home Screen'. Native iOS and Android apps are coming soon."},
    {"keywords": ["wecare", "about", "company", "who", "what", "platform"], "question": "What is WECARE.DIGITAL?", "answer": "WECARE.DIGITAL is a microservice company providing customer engagement solutions via WhatsApp Business API, multi-channel messaging, AI support, payments, and order management."},
    {"keywords": ["gift", "card", "voucher", "present", "gifting"], "question": "Can I buy a gift card?", "answer": "Yes! Visit wecare.digital/gift-card to purchase a gift card for any amount with a personal message. Delivered digitally, redeemable at our store."},
]

SERVICES_INFO = {
    'whatsapp': {
        'name': 'WhatsApp Business API',
        'description': 'Professional WhatsApp messaging for businesses',
        'features': ['Automated responses', 'Bulk messaging', 'Rich media support', 'Analytics']
    },
    'sms': {
        'name': 'SMS Services',
        'description': 'Reliable SMS delivery across India',
        'features': ['Transactional SMS', 'Promotional SMS', 'OTP delivery', 'DLT compliant']
    },
    'voice': {
        'name': 'Voice Services',
        'description': 'Automated voice calls and IVR',
        'features': ['Text-to-speech', 'Call recording', 'IVR menus', 'Call analytics']
    },
    'ecommerce': {
        'name': 'E-commerce Solutions',
        'description': 'Complete online store management',
        'features': ['Product catalog', 'Payment gateway', 'Order management', 'Inventory tracking']
    }
}


# Synonym map for improved keyword matching (Fix #11)
SYNONYMS = {
    'pricing': 'price', 'prices': 'price', 'cost': 'cost', 'costs': 'cost',
    'payments': 'payment', 'paying': 'pay',
    'orders': 'order', 'ordering': 'order', 'ordered': 'order',
    'deliveries': 'delivery', 'delivered': 'delivery', 'delivering': 'delivery',
    'shipped': 'shipping', 'ships': 'shipping',
    'returns': 'return', 'returned': 'return', 'returning': 'return',
    'refunds': 'refund', 'refunded': 'refund',
    'cancels': 'cancel', 'cancelled': 'cancel', 'cancellation': 'cancel',
    'exchanges': 'exchange', 'exchanged': 'exchange',
    'tracking': 'track', 'tracked': 'track',
    'invoices': 'invoice', 'billing': 'bill', 'billed': 'bill',
    'accounts': 'account', 'logged': 'login', 'logging': 'login', 'signin': 'login', 'sign-in': 'login',
    'registered': 'register', 'registration': 'register', 'registering': 'register',
    'signed': 'signup', 'signing': 'signup',
    'called': 'call', 'calling': 'call',
    'emailed': 'email', 'emailing': 'email', 'emails': 'email',
    'helped': 'help', 'helping': 'help',
    'contacted': 'contact', 'contacting': 'contact',
    'purchased': 'purchase', 'purchasing': 'purchase', 'purchases': 'purchase',
    'shopping': 'shop', 'shopped': 'shop',
    'products': 'product',
    'charges': 'charge', 'charged': 'charge', 'charging': 'charge',
    'fees': 'fee',
    'discounts': 'discount', 'discounted': 'discount',
    'wholesale': 'bulk',
    'timings': 'timing', 'timetable': 'timing',
    'opened': 'open', 'opening': 'open',
    'closed': 'close', 'closing': 'close',
    'available': 'available', 'availability': 'available',
}


DEFAULT_RESPONSE = "I don't have specific information about that. Please contact us at +91 9330994400 or one@wecare.digital for assistance."


# Fix #9: FAQ search quality monitoring
import logging as _logging
_faq_logger = _logging.getLogger('faq_search')


def _normalize_query(query: str) -> str:
    """Expand synonyms in query for better matching."""
    words = query.lower().split()
    expanded = []
    for w in words:
        expanded.append(SYNONYMS.get(w, w))
    return ' '.join(expanded)


def search_knowledge_base(query: str, max_results: int = 3) -> str:
    """
    Search the static knowledge base using keyword matching with synonym expansion.

    Args:
        query: User's question or search query
        max_results: Maximum number of results to return

    Returns:
        Formatted string with relevant answers
    """
    query_normalized = _normalize_query(query)
    matches = []

    for faq in FAQ_DATABASE:
        score = sum(1 for kw in faq['keywords'] if kw in query_normalized)
        if score > 0:
            matches.append((score, faq))

    matches.sort(key=lambda x: x[0], reverse=True)
    top = matches[:max_results]

    if not top:
        _faq_logger.info(f"faq_no_match|query={query[:100]}|normalized={query_normalized[:100]}")
        return DEFAULT_RESPONSE

    matched_ids = [faq['question'][:40] for _, faq in top]
    _faq_logger.info(f"faq_match|query={query[:60]}|matches={len(top)}|top={matched_ids[0]}|score={top[0][0]}")

    results = []
    for score, faq in top:
        results.append(f"Q: {faq['question']}\nA: {faq['answer']}")

    return '\n\n'.join(results)


def get_brand_info() -> dict:
    """Get brand information."""
    return BRAND_INFO


def get_service_info(service_name: str = None) -> dict:
    """Get information about services."""
    if service_name and service_name.lower() in SERVICES_INFO:
        return SERVICES_INFO[service_name.lower()]
    return SERVICES_INFO
