"""
Static Knowledge Base - Free Alternative to OpenSearch

AUTO-GENERATED by scripts/sync_faq.py from shared/faq-config.json
Do NOT edit manually — edit shared/faq-config.json and run: python scripts/sync_faq.py
"""

BRAND_INFO = {
    "name": "WECARE.DIGITAL",
    "website": "https://wecare.digital",
    "store": "https://wecare.digital/shop/",
    "email": "one@wecare.digital",
    "phone": "+91 9330994400",
    "whatsapp": "+91 9330994400"
}

FAQ_CONFIG = {'brand': {'name': 'WECARE.DIGITAL',
           'website': 'https://wecare.digital',
           'store': 'https://wecare.digital/shop/',
           'email': 'one@wecare.digital',
           'phone': '+91 9330994400',
           'whatsapp': '+91 9330994400'},
 'faqs': [{'id': 'hours',
           'keywords': ['hours', 'timing', 'open', 'close', 'available', 'when', 'time'],
           'category': 'general',
           'question': 'What are your business hours?',
           'answer': 'Browse the website at any time. For help, contact +91 9330994400 or '
                     'one@wecare.digital.',
           'shortAnswer': 'Contact our team for support'},
          {'id': 'contact',
           'keywords': ['contact', 'reach', 'call', 'email', 'phone', 'support', 'help'],
           'category': 'general',
           'question': 'How can I contact you?',
           'answer': 'You can reach us via:\\n• Phone/WhatsApp: +91 9330994400\\n• Email: '
                     'one@wecare.digital\\n• Website: https://wecare.digital',
           'shortAnswer': 'Call +91 9330994400 or email one@wecare.digital'},
          {'id': 'order',
           'keywords': ['order', 'buy', 'purchase', 'shop', 'product', 'cart'],
           'category': 'orders',
           'question': 'How do I place an order?',
           'answer': 'Browse products at https://wecare.digital/shop/. Verify your WhatsApp number '
                     'on the website to continue to checkout.',
           'shortAnswer': 'Browse wecare.digital/shop/'},
          {'id': 'payment',
           'keywords': ['payment', 'pay', 'price', 'cost', 'fee', 'charge', 'upi', 'card'],
           'category': 'payments',
           'question': 'What payment methods do you accept?',
           'answer': 'Razorpay Standard Checkout supports UPI, cards and net banking when checkout '
                     'is available. Review the final taxes and 2.5% convenience fee before paying.',
           'shortAnswer': 'Razorpay: UPI, cards and net banking'},
          {'id': 'delivery',
           'keywords': ['delivery', 'shipping', 'ship', 'courier', 'dispatch', 'send'],
           'category': 'orders',
           'question': 'What are your delivery options?',
           'answer': 'We offer standard shipping across India. Delivery time varies by location '
                     '(typically 3-7 business days). Track your order status in the My Orders '
                     'section.',
           'shortAnswer': '3-7 days across India'},
          {'id': 'return',
           'keywords': ['return', 'refund', 'cancel', 'exchange', 'money back'],
           'category': 'orders',
           'question': 'What is your return policy?',
           'answer': 'Returns are accepted within 7 days of delivery for eligible items. Contact '
                     'us at one@wecare.digital with your order number to initiate a return. '
                     'Refunds are processed within 5-7 business days.',
           'shortAnswer': '7-day return policy'},
          {'id': 'track',
           'keywords': ['track', 'status', 'where', 'order status', 'tracking'],
           'category': 'orders',
           'question': 'How do I track my order?',
           'answer': 'Visit https://wecare.digital/orders/ and contact us with your order '
                     'reference for the current status.',
           'shortAnswer': 'Check wecare.digital/orders/'},
          {'id': 'whatsapp',
           'keywords': ['whatsapp', 'message', 'chat', 'wa', 'messenger'],
           'category': 'general',
           'question': 'Can I order via WhatsApp?',
           'answer': 'Use WhatsApp to verify your number at '
                     'https://wecare.digital/account/sign-in/ and contact us for help. Browse '
                     'products at https://wecare.digital/shop/; payment checkout is on the '
                     'website.',
           'shortAnswer': 'WhatsApp verification; website checkout'},
          {'id': 'invoice',
           'keywords': ['invoice', 'bill', 'receipt', 'gst', 'tax'],
           'category': 'payments',
           'question': 'How do I get my invoice?',
           'answer': 'For a receipt from an existing payment, contact us with your order reference '
                     'through https://wecare.digital/orders/.',
           'shortAnswer': 'Contact us with your order reference'},
          {'id': 'account',
           'keywords': ['account', 'login', 'register', 'signup', 'password', 'profile'],
           'category': 'general',
           'question': 'How do I create an account?',
           'answer': 'Verify your WhatsApp number at https://wecare.digital/account/sign-in/ to '
                     'continue to your cart or orders.',
           'shortAnswer': 'Verify your WhatsApp number at wecare.digital/account/sign-in/'},
          {'id': 'convenience-fee',
           'keywords': ['convenience fee', 'extra charge', 'additional fee', 'why charge'],
           'category': 'payments',
           'question': 'What is the convenience fee?',
           'answer': 'The checkout policy uses a 2.5% convenience fee on the approved collection '
                     'amount and 18% GST on that fee. Review the server-confirmed tax and fee '
                     'breakdown before payment.',
           'shortAnswer': '2.5% convenience fee; review tax breakdown'},
          {'id': 'bulk-order',
           'keywords': ['bulk', 'wholesale', 'large order', 'quantity', 'discount'],
           'category': 'orders',
           'question': 'Do you offer bulk order discounts?',
           'answer': 'Yes! For bulk orders, please contact us at one@wecare.digital or call +91 '
                     '9330994400. We offer special pricing for large quantities.',
           'shortAnswer': 'Contact us for bulk pricing'}],
 'greetings': {'keywords': ['hi', 'hello', 'hey', 'namaste', 'good morning', 'good evening'],
               'response': 'Hi! 👋 Welcome to WECARE.DIGITAL. How can I help you today?'},
 'defaultResponse': "I don't have specific information about that. Please contact us at +91 "
                    '9330994400 or one@wecare.digital for assistance.'}

FAQ_DATABASE = [
    {"keywords": ["hours", "timing", "open", "close", "available", "when", "time"], "question": "What are your business hours?", "answer": "Browse the website at any time. For help, contact +91 9330994400 or one@wecare.digital."},
    {"keywords": ["contact", "reach", "call", "email", "phone", "support", "help"], "question": "How can I contact you?", "answer": "You can reach us via:\\n• Phone/WhatsApp: +91 9330994400\\n• Email: one@wecare.digital\\n• Website: https://wecare.digital"},
    {"keywords": ["order", "buy", "purchase", "shop", "product", "cart"], "question": "How do I place an order?", "answer": "Browse products at https://wecare.digital/shop/. Verify your WhatsApp number on the website to continue to checkout."},
    {"keywords": ["payment", "pay", "price", "cost", "fee", "charge", "upi", "card"], "question": "What payment methods do you accept?", "answer": "Razorpay Standard Checkout supports UPI, cards and net banking when checkout is available. Review the final taxes and 2.5% convenience fee before paying."},
    {"keywords": ["delivery", "shipping", "ship", "courier", "dispatch", "send"], "question": "What are your delivery options?", "answer": "We offer standard shipping across India. Delivery time varies by location (typically 3-7 business days). Track your order status in the My Orders section."},
    {"keywords": ["return", "refund", "cancel", "exchange", "money back"], "question": "What is your return policy?", "answer": "Returns are accepted within 7 days of delivery for eligible items. Contact us at one@wecare.digital with your order number to initiate a return. Refunds are processed within 5-7 business days."},
    {"keywords": ["track", "status", "where", "order status", "tracking"], "question": "How do I track my order?", "answer": "Visit https://wecare.digital/orders/ and contact us with your order reference for the current status."},
    {"keywords": ["whatsapp", "message", "chat", "wa", "messenger"], "question": "Can I order via WhatsApp?", "answer": "Use WhatsApp to verify your number at https://wecare.digital/account/sign-in/ and contact us for help. Browse products at https://wecare.digital/shop/; payment checkout is on the website."},
    {"keywords": ["invoice", "bill", "receipt", "gst", "tax"], "question": "How do I get my invoice?", "answer": "For a receipt from an existing payment, contact us with your order reference through https://wecare.digital/orders/."},
    {"keywords": ["account", "login", "register", "signup", "password", "profile"], "question": "How do I create an account?", "answer": "Verify your WhatsApp number at https://wecare.digital/account/sign-in/ to continue to your cart or orders."},
    {"keywords": ["convenience fee", "extra charge", "additional fee", "why charge"], "question": "What is the convenience fee?", "answer": "The checkout policy uses a 2.5% convenience fee on the approved collection amount and 18% GST on that fee. Review the server-confirmed tax and fee breakdown before payment."},
    {"keywords": ["bulk", "wholesale", "large order", "quantity", "discount"], "question": "Do you offer bulk order discounts?", "answer": "Yes! For bulk orders, please contact us at one@wecare.digital or call +91 9330994400. We offer special pricing for large quantities."},
]

SERVICES_INFO = {
    'whatsapp': {
        'name': 'WhatsApp Business API',
        'description': 'Professional WhatsApp messaging for businesses',
        'features': ['Automated responses', 'Bulk messaging', 'Rich media support', 'Analytics']
    },
    'sms': {
        'name': 'SMS Services',
        'description': 'Reliable SMS delivery across India',
        'features': ['Transactional SMS', 'Promotional SMS', 'OTP delivery', 'DLT compliant']
    },
    'voice': {
        'name': 'Voice Services',
        'description': 'Automated voice calls and IVR',
        'features': ['Text-to-speech', 'Call recording', 'IVR menus', 'Call analytics']
    },
    'ecommerce': {
        'name': 'E-commerce Solutions',
        'description': 'Complete online store management',
        'features': ['Product catalog', 'Payment gateway', 'Order management', 'Inventory tracking']
    }
}


# Synonym map for improved keyword matching (Fix #11)
SYNONYMS = {
    'pricing': 'price', 'prices': 'price', 'cost': 'cost', 'costs': 'cost',
    'payments': 'payment', 'paying': 'pay',
    'orders': 'order', 'ordering': 'order', 'ordered': 'order',
    'deliveries': 'delivery', 'delivered': 'delivery', 'delivering': 'delivery',
    'shipped': 'shipping', 'ships': 'shipping',
    'returns': 'return', 'returned': 'return', 'returning': 'return',
    'refunds': 'refund', 'refunded': 'refund',
    'cancels': 'cancel', 'cancelled': 'cancel', 'cancellation': 'cancel',
    'exchanges': 'exchange', 'exchanged': 'exchange',
    'tracking': 'track', 'tracked': 'track',
    'invoices': 'invoice', 'billing': 'bill', 'billed': 'bill',
    'accounts': 'account', 'logged': 'login', 'logging': 'login', 'signin': 'login', 'sign-in': 'login',
    'registered': 'register', 'registration': 'register', 'registering': 'register',
    'signed': 'signup', 'signing': 'signup',
    'called': 'call', 'calling': 'call',
    'emailed': 'email', 'emailing': 'email', 'emails': 'email',
    'helped': 'help', 'helping': 'help',
    'contacted': 'contact', 'contacting': 'contact',
    'purchased': 'purchase', 'purchasing': 'purchase', 'purchases': 'purchase',
    'shopping': 'shop', 'shopped': 'shop',
    'products': 'product',
    'charges': 'charge', 'charged': 'charge', 'charging': 'charge',
    'fees': 'fee',
    'discounts': 'discount', 'discounted': 'discount',
    'wholesale': 'bulk',
    'timings': 'timing', 'timetable': 'timing',
    'opened': 'open', 'opening': 'open',
    'closed': 'close', 'closing': 'close',
    'available': 'available', 'availability': 'available',
}


DEFAULT_RESPONSE = "I don't have specific information about that. Please contact us at +91 9330994400 or one@wecare.digital for assistance."


# Fix #9: FAQ search quality monitoring
import logging as _logging
_faq_logger = _logging.getLogger('faq_search')


def _normalize_query(query: str) -> str:
    """Expand synonyms in query for better matching."""
    words = query.lower().split()
    expanded = []
    for w in words:
        expanded.append(SYNONYMS.get(w, w))
    return ' '.join(expanded)


def search_knowledge_base(query: str, max_results: int = 3) -> str:
    """
    Search the static knowledge base using keyword matching with synonym expansion.

    Args:
        query: User's question or search query
        max_results: Maximum number of results to return

    Returns:
        Formatted string with relevant answers
    """
    query_normalized = _normalize_query(query)
    matches = []

    for faq in FAQ_DATABASE:
        score = sum(1 for kw in faq['keywords'] if kw in query_normalized)
        if score > 0:
            matches.append((score, faq))

    matches.sort(key=lambda x: x[0], reverse=True)
    top = matches[:max_results]

    if not top:
        _faq_logger.info(f"faq_no_match|query={query[:100]}|normalized={query_normalized[:100]}")
        return DEFAULT_RESPONSE

    matched_ids = [faq['question'][:40] for _, faq in top]
    _faq_logger.info(f"faq_match|query={query[:60]}|matches={len(top)}|top={matched_ids[0]}|score={top[0][0]}")

    results = []
    for score, faq in top:
        results.append(f"Q: {faq['question']}\nA: {faq['answer']}")

    return '\n\n'.join(results)


def get_brand_info() -> dict:
    """Get brand information."""
    return BRAND_INFO


def get_service_info(service_name: str = None) -> dict:
    """Get information about services."""
    if service_name and service_name.lower() in SERVICES_INFO:
        return SERVICES_INFO[service_name.lower()]
    return SERVICES_INFO
