"""The one place the Meta Graph API version is decided.

Spec tasks R1.1-R1.3 (`.kiro/specs/whatsapp-wix-commerce`).

WHAT THIS REPLACES. `META_API_VERSION = 'v25.0'` was declared at module scope in
**eleven** handlers -- five reading the environment with a hard-coded default, six not
reading it at all -- and the version was additionally embedded in **five** request URLs
as a literal. So a Graph version bump was a sixteen-file edit where six of the files
would silently ignore the environment variable you set, and nothing failed if you missed
one: the old version keeps working until Meta retires it, which is exactly when you find
out.

The spec counted 7 and 3. It is 11 and 5; the numbers here were re-derived rather than
carried over.

WHY A MODULE AND NOT JUST THE ENVIRONMENT VARIABLE. Two reasons a variable alone does not
give:

1. **It validates, and fails at import.** A malformed value (`v25`, `25.0`, `latest`,
   `v25.0.1`) does not produce a helpful error at request time -- it produces a 400 from
   Graph with a message about an unknown path, which reads like an application bug. This
   raises `MetaVersionError` on import instead, so a bad deploy fails at initialisation
   where the stack trace names the cause.
2. **It is one symbol to grep.** `from lambda_utils.meta_version import META_API_VERSION`
   in every consumer means the next bump is one line, and
   `tests/test_meta_version.py` fails if a handler reintroduces a local declaration or a
   URL literal.

AGREEMENT WITH `config/vendor-versions.json`. That file already carries
`metaGraphApiVersion`, generated by `scripts/check-versions.ts`. It is the source for the
TypeScript side; this is the source for the Python side, and a test asserts the two match
so they cannot drift apart silently. Neither is derived from the other at runtime,
because a Lambda should not read a repo file to learn its own configuration.
"""

from __future__ import annotations

import os
import re

#: `vNN.N` exactly. Meta's Graph versions are always major.minor with a single-digit
#: minor, e.g. `v25.0`. Anything else is a typo, not a version we have not seen yet --
#: and accepting a typo means discovering it from a Graph 400 at request time.
_VERSION_RE = re.compile(r"^v\d{1,3}\.\d$")

GRAPH_HOST = "https://graph.facebook.com"

#: The default is pinned rather than "latest" on purpose. A floating version means a
#: vendor-side release can change this application's behaviour with no deploy and no
#: commit, which is the opposite of what `docs/compatibility.md` exists to record.
_DEFAULT = "v25.0"


class MetaVersionError(ValueError):
    """Raised at import when META_API_VERSION is not a Graph version."""


def _resolve() -> str:
    # ABSENT and EMPTY are deliberately different. Absent means "no opinion", so the
    # pinned default applies. Explicitly set to "" means someone configured it and got it
    # wrong -- probably an unresolved substitution in a deploy template -- and silently
    # defaulting would hide exactly the mistake this module exists to surface.
    configured = os.environ.get("META_API_VERSION")
    raw = (_DEFAULT if configured is None else configured).strip()
    if not _VERSION_RE.match(raw):
        raise MetaVersionError(
            f"META_API_VERSION={raw!r} is not a Meta Graph version. Expected the form "
            f"'v25.0' (a 'v', a major number, a dot, a single-digit minor). Refusing to "
            f"start rather than letting Graph answer 400 for an unknown path at request "
            f"time."
        )
    return raw


#: Import-time, deliberately. A handler that cannot resolve its API version has nothing
#: useful to do, and failing in the init phase puts the reason in the first log line
#: instead of in every subsequent request.
META_API_VERSION: str = _resolve()

#: `https://graph.facebook.com/v25.0`
GRAPH_BASE: str = f"{GRAPH_HOST}/{META_API_VERSION}"


def graph_url(*parts: str) -> str:
    """Build a versioned Graph URL from path segments.

        graph_url('1016149501586345', 'messages')
        -> 'https://graph.facebook.com/v25.0/1016149501586345/messages'

    Use this instead of an f-string with the version in it. The five remaining URL
    literals were found only because someone grepped for `graph.facebook.com/v`; a
    helper means the next one cannot be written by accident.
    """
    cleaned = [str(p).strip("/") for p in parts if str(p).strip("/")]
    return "/".join([GRAPH_BASE, *cleaned])


def is_valid_version(candidate: str) -> bool:
    """Whether `candidate` would be accepted. Exposed for tests and health endpoints."""
    return bool(_VERSION_RE.match((candidate or "").strip()))
