"""Shared WhatsApp/Meta constants and enums."""

GRAPH_BASE = 'https://graph.facebook.com'
DEFAULT_API_VERSION = 'v25.0'

TEMPLATE_CATEGORIES = ('MARKETING', 'UTILITY', 'AUTHENTICATION')

HEADER_FORMATS = ('TEXT', 'IMAGE', 'VIDEO', 'GIF', 'DOCUMENT', 'LOCATION')

BUTTON_TYPES = (
    'QUICK_REPLY', 'URL', 'PHONE_NUMBER', 'COPY_CODE', 'VOICE_CALL',
    'OTP', 'MPM', 'SPM', 'CATALOG', 'FLOW', 'REQUEST_CONTACT_INFO',
)

# message_send_ttl_seconds bounds per category (None = use -1 30d sentinel allowed)
TTL_BOUNDS = {
    'AUTHENTICATION': (30, 900),
    'UTILITY': (30, 43200),
    'MARKETING': (43200, 2592000),
}
TTL_NEG1_ALLOWED = {'AUTHENTICATION', 'UTILITY'}

PERMISSION_TASKS = (
    'MANAGE', 'DEVELOP', 'MANAGE_TEMPLATES', 'MANAGE_PHONE', 'VIEW_COST',
    'MANAGE_EXTENSIONS', 'VIEW_PHONE_ASSETS', 'MANAGE_PHONE_ASSETS', 'VIEW_TEMPLATES', 'MESSAGING',
)

ASSIGNED_USER_TYPES = ('BUSINESS_USER', 'SYSTEM_USER', 'PERSONAL_USER')

SCHEDULE_STATUSES = ('COMPLETED', 'FAILED', 'SCHEDULED', 'SENDING')

JOIN_APPROVAL_MODES = ('approval_required', 'auto_approve')

# Pricing categories (analytics + webhooks)
PRICING_CATEGORY_AI_ANALYTICS = 'AI_BOT'
PRICING_CATEGORY_AI_WEBHOOK = 'general_purpose_ai'

# Group limits
GROUP_SUBJECT_MAX = 128
GROUP_DESCRIPTION_MAX = 2048

# Component text limits
HEADER_TEXT_MAX = 60
BODY_TEXT_MAX = 1024
FOOTER_TEXT_MAX = 60
BUTTON_TEXT_MAX = 25
COPY_CODE_EXAMPLE_MAX = 20
PHONE_NUMBER_MAX = 20
URL_MAX = 2000
FLOW_NAME_MAX = 200
