import { defineFunction } from '@aws-amplify/backend';

export const inboundWhatsappHandler = defineFunction({
  name: 'wecare-inbound-whatsapp',
  entry: './handler.py',
  runtime: 20,
  timeoutSeconds: 60,
  memoryMB: 512,
  environment: {
    AWS_REGION: 'us-east-1',
    LOG_LEVEL: 'INFO',
    SEND_MODE: 'LIVE',
    CONTACTS_TABLE: 'base-wecare-digital-ContactsTable',
    MESSAGES_TABLE: 'base-wecare-digital-WhatsAppInboundTable',
    OUTBOUND_TABLE: 'base-wecare-digital-WhatsAppOutboundTable',
    MEDIA_FILES_TABLE: 'base-wecare-digital-MediaFilesTable',
    SYSTEM_CONFIG_TABLE: 'base-wecare-digital-SystemConfigTable',
    AI_INTERACTIONS_TABLE: 'base-wecare-digital-AIInteractionsTable',
    MEDIA_BUCKET: 'app.wecare.digital',
    S3_BUCKET: 'app.wecare.digital',
    MEDIA_INBOUND_PREFIX: 'whatsapp-media/whatsapp-media-incoming/',
    SNS_TOPIC_ARN: 'arn:aws:sns:us-east-1:775261844268:base-wecare-digital',
    INBOUND_DLQ_URL: 'https://sqs.us-east-1.amazonaws.com/775261844268/base-wecare-digital-inbound-dlq',
    OUTBOUND_WHATSAPP_FUNCTION: 'wecare-outbound-whatsapp',
    AI_QUERY_KB_FUNCTION: 'wecare-ai-query-kb',
    AI_GENERATE_RESPONSE_FUNCTION: 'wecare-ai-generate-response',
    WHATSAPP_PHONE_NUMBER_ID_1: 'phone-number-id-5e020cecd221429996f6ae721cc42206',
    WHATSAPP_PHONE_NUMBER_ID_2: 'phone-number-id-abdd81f7bec24ec085a25ab9df6a6f7c',
  },
});
