/**
 * FAQ Search Utility - Frontend
 *
 * AUTO-GENERATED by scripts/sync_faq.py from shared/faq-config.json
 * Do NOT edit manually — edit shared/faq-config.json and run: python scripts/sync_faq.py
 */

export interface FAQ {
  id: string;
  keywords: string[];
  category: string;
  question: string;
  answer: string;
  shortAnswer: string;
}

export interface FAQSearchResult {
  id: string;
  question: string;
  answer: string;
  score: number;
  category: string;
  matchedKeywords: string[];
}

export interface BrandInfo {
  name: string;
  website: string;
  store: string;
  email: string;
  phone: string;
  whatsapp: string;
}

// FAQ Database — auto-generated from shared/faq-config.json
const FAQ_DATABASE: FAQ[] = [
  {
    id: "hours",
    keywords: [ "hours", "timing", "open", "close", "available", "when", "time" ],
    category: "general",
    question: "What are your business hours?",
    answer: "We are available 24/7 for online orders and support. For urgent assistance, call us at +91 9330994400 or email one@wecare.digital.",
    shortAnswer: "24/7 available",
  },
  {
    id: "contact",
    keywords: [ "contact", "reach", "call", "email", "phone", "support", "help" ],
    category: "general",
    question: "How can I contact you?",
    answer: "You can reach us via:\n\u2022 Phone/WhatsApp: +91 9330994400\n\u2022 Email: one@wecare.digital\n\u2022 Website: https://wecare.digital",
    shortAnswer: "Call +91 9330994400 or email one@wecare.digital",
  },
  {
    id: "order",
    keywords: [ "order", "buy", "purchase", "shop", "product", "cart" ],
    category: "orders",
    question: "How do I place an order?",
    answer: "Visit our store at https://store.wecare.digital to browse products and place orders. You can also order via WhatsApp by sending us a message at +91 9330994400.",
    shortAnswer: "Visit store.wecare.digital or WhatsApp us",
  },
  {
    id: "payment",
    keywords: [ "payment", "pay", "price", "cost", "fee", "charge", "upi", "card" ],
    category: "payments",
    question: "What payment methods do you accept?",
    answer: "We accept:\n\u2022 UPI (Google Pay, PhonePe, Paytm)\n\u2022 Credit/Debit Cards\n\u2022 Net Banking\n\u2022 Razorpay Payment Gateway\n\nA 2.2% convenience fee + 18% GST applies to all payments.",
    shortAnswer: "UPI, Cards, Net Banking (2.2% + GST fee applies)",
  },
  {
    id: "delivery",
    keywords: [ "delivery", "shipping", "ship", "courier", "dispatch", "send" ],
    category: "orders",
    question: "What are your delivery options?",
    answer: "We offer standard shipping across India. Delivery time varies by location (typically 3-7 business days). Track your order status in the My Orders section.",
    shortAnswer: "3-7 days across India",
  },
  {
    id: "return",
    keywords: [ "return", "refund", "cancel", "exchange", "money back" ],
    category: "orders",
    question: "What is your return policy?",
    answer: "Returns are accepted within 7 days of delivery for eligible items. Contact us at one@wecare.digital with your order number to initiate a return. Refunds are processed within 5-7 business days.",
    shortAnswer: "7-day return policy",
  },
  {
    id: "track",
    keywords: [ "track", "status", "where", "order status", "tracking" ],
    category: "orders",
    question: "How do I track my order?",
    answer: "Log in to your account at https://store.wecare.digital and visit the My Orders page to track your order status in real-time.",
    shortAnswer: "Check My Orders page",
  },
  {
    id: "whatsapp",
    keywords: [ "whatsapp", "message", "chat", "wa", "messenger" ],
    category: "general",
    question: "Can I order via WhatsApp?",
    answer: "Yes! Send us a message on WhatsApp at +91 9330994400. Our AI assistant will help you browse products and place orders directly through chat.",
    shortAnswer: "Yes, WhatsApp +91 9330994400",
  },
  {
    id: "invoice",
    keywords: [ "invoice", "bill", "receipt", "gst", "tax" ],
    category: "payments",
    question: "How do I get my invoice?",
    answer: "Your invoice is automatically generated after payment and sent to your registered email. You can also download it from the My Orders section or request it via email.",
    shortAnswer: "Check email or My Orders page",
  },
  {
    id: "account",
    keywords: [ "account", "login", "register", "signup", "password", "profile" ],
    category: "general",
    question: "How do I create an account?",
    answer: "Visit https://store.wecare.digital and click on the account icon to register. You can also place orders as a guest without creating an account.",
    shortAnswer: "Click account icon on store.wecare.digital",
  },
  {
    id: "convenience-fee",
    keywords: [ "convenience fee", "extra charge", "additional fee", "why charge" ],
    category: "payments",
    question: "What is the convenience fee?",
    answer: "A 2.2% convenience fee is charged on the cart total, plus 18% GST on that fee. This covers payment gateway and processing costs. Total fee = (Cart \u00d7 2.2%) \u00d7 1.18",
    shortAnswer: "2.2% + 18% GST on payment processing",
  },
  {
    id: "bulk-order",
    keywords: [ "bulk", "wholesale", "large order", "quantity", "discount" ],
    category: "orders",
    question: "Do you offer bulk order discounts?",
    answer: "Yes! For bulk orders, please contact us at one@wecare.digital or call +91 9330994400. We offer special pricing for large quantities.",
    shortAnswer: "Contact us for bulk pricing",
  },
  {
    id: "submit-request",
    keywords: [ "submit", "request", "service", "help", "issue", "problem", "complaint" ],
    category: "general",
    question: "How do I submit a request?",
    answer: "You can submit a service request in two ways:\n\u2022 Via WhatsApp: Send a message to +91 9330994400 and select 'Submit Request' from the menu.\n\u2022 Via Web: Go to Service \u2192 Submit Request in the Bharat Stack dashboard.\n\nYou will need to select your order first, then describe your issue. Requests are tracked by Order ID.",
    shortAnswer: "WhatsApp menu or Service \u2192 Submit Request on web",
  },
  {
    id: "track-request",
    keywords: [ "track", "request", "status", "check", "progress", "update", "follow" ],
    category: "general",
    question: "How can I track my request?",
    answer: "Track your request by Order ID:\n\u2022 Via WhatsApp: Select 'Track Request' from the menu and enter your Order ID.\n\u2022 Via Web: Go to Service \u2192 Track Request in the dashboard.\n\nYou will see all service requests, status timeline, payment info, and linked documents for that order.",
    shortAnswer: "Service \u2192 Track Request, search by Order ID",
  },
  {
    id: "amend-request",
    keywords: [ "amend", "change", "modify", "update", "edit", "correct", "amendment" ],
    category: "general",
    question: "How do I request an amendment?",
    answer: "To amend an existing request:\n\u2022 Via WhatsApp: Select 'Amend Request' from the menu.\n\u2022 Via Web: Go to Service \u2192 Amend Request.\n\nSelect your order, choose the request to amend, describe the changes needed, and submit. Amendment history is tracked and visible to both you and the admin team.",
    shortAnswer: "Service \u2192 Amend Request, select order and request",
  },
  {
    id: "rx-slot",
    keywords: [ "rx", "slot", "prescription", "pharmacy", "medicine", "medical", "schedule" ],
    category: "general",
    question: "How do I book or reschedule an RX slot?",
    answer: "Book an RX slot for prescriptions or medical consultations:\n\u2022 Via WhatsApp: Select 'RX Slot' from the self-service menu.\n\u2022 Via Web: Go to Booking \u2192 RX Slots.\n\nChoose your preferred date, time, and provider. You can reschedule or cancel from the same page.",
    shortAnswer: "Booking \u2192 RX Slots or WhatsApp menu",
  },
  {
    id: "drop-docs",
    keywords: [ "document", "upload", "docs", "drop", "file", "prescription", "id", "proof" ],
    category: "general",
    question: "How do I upload supporting documents?",
    answer: "Upload documents in two ways:\n\u2022 Via WhatsApp: Simply send the document (photo, PDF, etc.) to +91 9330994400. It will automatically appear in our system.\n\u2022 Via Web: Go to Drop Docs in the dashboard.\n\nDocuments are reviewed by our team. You can check the status (uploaded, under review, approved, rejected) anytime.",
    shortAnswer: "Send via WhatsApp or use Drop Docs on web",
  },
  {
    id: "enterprise-support",
    keywords: [ "enterprise", "business", "corporate", "b2b", "company", "technical" ],
    category: "general",
    question: "How do I get enterprise support?",
    answer: "For enterprise and business support:\n\u2022 Via WhatsApp: Select 'Enterprise Assist' from the menu.\n\u2022 Via Web: Go to Enterprise in the dashboard.\n\nProvide your company details, describe the issue, and set priority. Cases are assigned to dedicated support agents and tracked through resolution.",
    shortAnswer: "Enterprise menu on WhatsApp or web dashboard",
  },
  {
    id: "appointment",
    keywords: [ "appointment", "book", "schedule", "consultation", "visit", "meeting" ],
    category: "general",
    question: "How do I book an appointment?",
    answer: "Book an appointment for consultations or service visits:\n\u2022 Via WhatsApp: Select 'Schedule Appointment' from the self-service menu.\n\u2022 Via Web: Go to Booking \u2192 Appointments.\n\nChoose appointment type, preferred date/time, and location. You will receive a confirmation and reminders via WhatsApp.",
    shortAnswer: "Booking \u2192 Appointments or WhatsApp menu",
  },
  {
    id: "leave-review",
    keywords: [ "review", "feedback", "rating", "rate", "experience", "opinion", "star" ],
    category: "general",
    question: "How do I leave a review?",
    answer: "Share your feedback:\n\u2022 Via WhatsApp: Select 'Leave Review' from the menu. Rate 1-5 stars and add comments.\n\u2022 Via Web: Go to Reviews in the dashboard.\n\nYour review helps us improve. Reviews are moderated and published after approval.",
    shortAnswer: "WhatsApp menu or Reviews on web dashboard",
  },
  {
    id: "mobile-app",
    keywords: [ "app", "mobile", "android", "ios", "iphone", "download", "install" ],
    category: "general",
    question: "Is there a mobile app?",
    answer: "Yes! The Bharat Stack platform is available as a Progressive Web App (PWA). Visit stack.wecare.digital on your mobile browser and tap 'Add to Home Screen' for an app-like experience. Native iOS and Android apps are coming soon.",
    shortAnswer: "PWA available, native apps coming soon",
  },
  {
    id: "what-is-wecare",
    keywords: [ "wecare", "about", "company", "who", "what", "platform", "service" ],
    category: "general",
    question: "What is WECARE.DIGITAL?",
    answer: "WECARE.DIGITAL is a microservice company that provides end-to-end customer engagement solutions. Our Bharat Stack platform offers WhatsApp Business API, multi-channel messaging (SMS, Email, Voice), AI-powered support, payment processing, and a complete order management system. We help businesses connect with customers across India.",
    shortAnswer: "Microservice company for customer engagement",
  },
  {
    id: "gift-card",
    keywords: [ "gift", "card", "voucher", "present", "gifting" ],
    category: "payments",
    question: "Can I buy a gift card?",
    answer: "Yes! Visit https://wecare.digital/gift-card to purchase a gift card for any amount. You can include a personal message. Gift cards are delivered digitally and can be redeemed at our store.",
    shortAnswer: "Yes, visit wecare.digital/gift-card",
  },
];

const BRAND_INFO: BrandInfo = {
  name: "WECARE.DIGITAL",
  website: "https://wecare.digital",
  store: "https://store.wecare.digital",
  email: "one@wecare.digital",
  phone: "+91 9330994400",
  whatsapp: "+91 9330994400",
};

// Synonym map for improved keyword matching
const SYNONYMS: Record<string, string> = {
  "pricing": "price",
  "prices": "price",
  "costs": "cost",
  "payments": "payment",
  "paying": "pay",
  "orders": "order",
  "ordering": "order",
  "ordered": "order",
  "deliveries": "delivery",
  "delivered": "delivery",
  "shipped": "shipping",
  "ships": "shipping",
  "returns": "return",
  "returned": "return",
  "refunds": "refund",
  "refunded": "refund",
  "cancels": "cancel",
  "cancelled": "cancel",
  "cancellation": "cancel",
  "exchanges": "exchange",
  "tracking": "track",
  "tracked": "track",
  "invoices": "invoice",
  "billing": "bill",
  "accounts": "account",
  "logging": "login",
  "signin": "login",
  "registered": "register",
  "registration": "register",
  "called": "call",
  "calling": "call",
  "emailed": "email",
  "emails": "email",
  "helped": "help",
  "helping": "help",
  "contacted": "contact",
  "contacting": "contact",
  "purchased": "purchase",
  "purchases": "purchase",
  "shopping": "shop",
  "products": "product",
  "charges": "charge",
  "charged": "charge",
  "fees": "fee",
  "discounts": "discount",
  "wholesale": "bulk",
  "timings": "timing",
  "opened": "open",
  "closed": "close",
};

const GREETINGS = [ "hi", "hello", "hey", "namaste", "good morning", "good evening" ];
const DEFAULT_RESPONSE = "I don't have specific information about that. Please contact us at +91 9330994400 or one@wecare.digital for assistance.";

function normalizeQuery ( query: string ): string {
  return query.toLowerCase().split( /\s+/ ).map( w => SYNONYMS[ w ] || w ).join( ' ' );
}

/**
 * Search FAQs using keyword matching with synonym expansion
 */
export function searchFAQs (
  query: string,
  options: { maxResults?: number; shortAnswer?: boolean; category?: string } = {}
): FAQSearchResult[] {
  const { maxResults = 3, shortAnswer = false, category } = options;
  const queryNorm = normalizeQuery( query.trim() );

  if ( !queryNorm ) return [];

  // Check for greetings
  if ( GREETINGS.some( g => queryNorm.includes( g ) ) )
  {
    return [ {
      id: 'greeting', question: 'Greeting',
      answer: "Hi! \ud83d\udc4b Welcome to WECARE.DIGITAL. How can I help you today?",
      score: 100, category: 'general', matchedKeywords: [ 'greeting' ]
    } ];
  }

  const matches: FAQSearchResult[] = [];

  for ( const faq of FAQ_DATABASE )
  {
    if ( category && faq.category !== category ) continue;
    let score = 0;
    const matchedKeywords: string[] = [];
    for ( const keyword of faq.keywords )
    {
      if ( queryNorm.includes( keyword.toLowerCase() ) )
      {
        score++;
        matchedKeywords.push( keyword );
      }
    }
    if ( score > 0 )
    {
      matches.push( {
        id: faq.id, question: faq.question,
        answer: shortAnswer ? faq.shortAnswer : faq.answer,
        score, category: faq.category, matchedKeywords
      } );
    }
  }

  return matches.sort( ( a, b ) => b.score - a.score ).slice( 0, maxResults );
}

/**
 * Get all FAQs grouped by category
 */
export function getAllFAQs ( shortAnswer: boolean = false ): Record<string, FAQ[]> {
  const grouped: Record<string, FAQ[]> = { general: [], orders: [], payments: [] };
  for ( const faq of FAQ_DATABASE )
  {
    if ( !grouped[ faq.category ] ) grouped[ faq.category ] = [];
    grouped[ faq.category ].push( faq );
  }
  return grouped;
}

/**
 * Get FAQ by ID
 */
export function getFAQById ( id: string ): FAQ | undefined {
  return FAQ_DATABASE.find( faq => faq.id === id );
}

/**
 * Get brand information
 */
export function getBrandInfo (): BrandInfo {
  return BRAND_INFO;
}

/**
 * Get formatted response text from search results
 */
export function formatSearchResponse ( results: FAQSearchResult[] ): string {
  if ( results.length === 0 ) return DEFAULT_RESPONSE;
  if ( results.length === 1 ) return results[ 0 ].answer;
  return results.map( r => `Q: ${r.question}\nA: ${r.answer}` ).join( '\n\n' );
}

/**
 * Get category display name
 */
export function getCategoryName ( category: string ): string {
  const names: Record<string, string> = { "general": "General Information", "orders": "Orders & Delivery", "payments": "Payments & Billing" };
  return names[ category ] || category;
}
