#!/usr/bin/env python3
"""Generate `docs/service-implementation-matrix.md` from measured state.

Why this is generated and not written
-------------------------------------
`bw-crm.md` asks for a matrix joining "frontend route/component, API method/path/auth,
Lambda/service physical name and source path, ... deployment owner, ... live evidence
and status" for every feature. Hand-writing that for 65 functions and 361 routes
produces a document that is wrong within a week - and the brief's own execution rule
says not to trust dated counts, which a hand-written matrix is made of.

So this reads `docs/execution/runtime-inventory.json`, which is itself generated by
`scripts/generate_runtime_inventory.py` from the live account plus the repository, and
emits the join. Regenerate both together:

    python scripts/generate_runtime_inventory.py
    python scripts/generate_service_matrix.py

What it deliberately does NOT claim
-----------------------------------
* It reports the **deploy owner**, not that a deploy happened.
* `routeCount` and traffic are measurements, not desired state. A function with zero
  invocations is a review candidate, not a defect.
* Frontend callers are matched by the route path appearing in a `src/**/*.ts(x)`
  file. That is a textual join, so it under-reports a path built by string
  concatenation and over-reports one mentioned in a comment. `117` route paths that
  no frontend file mentions are mostly provider webhooks and internal invocations.
* It says nothing about whether a test covers a function. Test-to-function mapping is
  not derivable from this data, and inventing a column for it would be the kind of
  confident-looking fiction this file exists to avoid.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
INVENTORY = REPO / "docs/execution/runtime-inventory.json"
OUT = REPO / "docs/service-implementation-matrix.md"


def load() -> dict:
    if not INVENTORY.is_file():
        raise SystemExit(
            f"{INVENTORY.relative_to(REPO)} is missing. Run "
            "`python scripts/generate_runtime_inventory.py` first."
        )
    return json.loads(INVENTORY.read_text())


def deploy_owner(fn: dict) -> str:
    """Who can actually ship a change to this function."""
    name = fn["function"]
    if fn.get("packageType") == "Image":
        return "GitHub Actions (container image)"
    if name == "wecare-seo-tools":
        return "`scripts/deploy_seo_tools.py`"
    if name == "wecare-get-miss-redirect":
        return "own deployer (Lambda@Edge, associates by version)"
    if fn.get("inDeployMap"):
        return "`deploy_all_lambdas.py`"
    return "**none — unpatchable**"


def esc(text: str) -> str:
    return str(text).replace("|", "\\|")


def main() -> int:
    inv = load()
    functions = sorted(inv["functions"], key=lambda f: f["function"])
    routes = inv["routes"]
    callers = inv.get("frontendCallersByRoutePath", {})
    counts = inv.get("counts", {})
    anomalies = inv.get("anomalies", {})

    routes_by_fn: dict[str, list[dict]] = {}
    for route in routes:
        routes_by_fn.setdefault(route.get("targetFunction") or "", []).append(route)

    md: list[str] = []
    md.append("# Service implementation matrix")
    md.append("")
    md.append(f"**Generated** by `scripts/generate_service_matrix.py` from "
              f"`docs/execution/runtime-inventory.json` (`{inv.get('generated')}`), "
              f"region `{inv.get('region')}`.")
    md.append("")
    md.append("Do not hand-edit. Regenerate:")
    md.append("")
    md.append("```bash")
    md.append("python scripts/generate_runtime_inventory.py")
    md.append("python scripts/generate_service_matrix.py")
    md.append("```")
    md.append("")
    md.append("## Totals")
    md.append("")
    md.append("| | Measured |")
    md.append("|---|---:|")
    for key in ("functions", "routes", "tables", "queues"):
        if key in counts:
            md.append(f"| {key} | {counts[key]} |")
    md.append(f"| functions with a `live` alias | "
              f"{sum(1 for f in functions if f.get('hasLiveAlias'))} |")
    md.append(f"| functions in the deploy map | "
              f"{sum(1 for f in functions if f.get('inDeployMap'))} |")
    md.append("")

    md.append("## Read this before drawing conclusions")
    md.append("")
    md.append("* **Deploy owner** is who *can* ship a change, not evidence that a "
              "deploy happened.")
    md.append("* **Frontend callers** is a textual join on the route path appearing in "
              "`src/**/*.ts(x)`. It under-reports paths built by concatenation and "
              "over-reports ones only mentioned in a comment.")
    md.append("* **Zero invocations** marks a review candidate, not a defect. A "
              "provider webhook can be legitimately idle.")
    md.append("* There is deliberately **no test-coverage column**. Test-to-function "
              "mapping is not derivable from this data, and a fabricated column would "
              "be worse than its absence.")
    md.append("")

    md.append("## Functions")
    md.append("")
    md.append("| Function | Source | Deploy owner | `live` | Routes | Inv 7d | Err 7d "
              "| Log ret. | Event sources |")
    md.append("|---|---|---|:-:|--:|--:|--:|--:|---|")
    for fn in functions:
        name = fn["function"]
        src = fn.get("sourcePath") or "—"
        live = "yes" if fn.get("hasLiveAlias") else "**no**"
        ret = fn.get("logRetentionDays")
        ret_s = str(ret) if ret else "**none**"
        err = fn.get("errors7d") or 0
        err_s = f"**{err:g}**" if err else "0"
        # eventSources are dicts: {arn, batchSize, enabled, state}. Show the ARN's
        # last segment plus whether it is actually enabled - a disabled mapping is
        # not a live trigger, and collapsing the two would hide that.
        # Loop variable is `event_source`, NOT `src`: `src` holds sourcePath above,
        # and reusing it here silently replaced the Source column with an event-source
        # dict - but only for the functions that have event sources, which is why it
        # looked like bad data for one row rather than a bug.
        evs_parts = []
        for event_source in fn.get("eventSources") or []:
            if isinstance(event_source, dict):
                label = (event_source.get("arn") or "?").rsplit(":", 1)[-1]
                if event_source.get("state") and event_source["state"] != "Enabled":
                    label += f" ({event_source['state']})"
                evs_parts.append(label)
            else:
                evs_parts.append(str(event_source))
        evs = ", ".join(evs_parts) or "—"
        md.append(
            f"| `{name}` | `{esc(src)}` | {deploy_owner(fn)} | {live} "
            f"| {fn.get('routeCount', 0)} | {fn.get('invocations7d', 0):g} | {err_s} "
            f"| {ret_s} | {esc(evs)} |"
        )
    md.append("")

    md.append("## Routes, and the frontend that calls them")
    md.append("")
    md.append("Grouped by target function. `auth` is the API Gateway "
              "`authorizationType`; `NONE` there does **not** mean unauthenticated - "
              "this fleet authenticates in the handler, which "
              "`scripts/audit_route_auth.py --gate` is what actually proves "
              "(0 OPEN at both layers).")
    md.append("")
    for fn_name in sorted(routes_by_fn):
        if not fn_name:
            continue
        md.append(f"### `{fn_name}`")
        md.append("")
        md.append("| Route | Qualifier | Gateway auth | Frontend files |")
        md.append("|---|---|---|---|")
        for route in sorted(routes_by_fn[fn_name], key=lambda r: r["routeKey"]):
            key = route["routeKey"]
            path = key.split(" ", 1)[-1]
            who = callers.get(path) or []
            who_s = ", ".join(f"`{Path(w).name}`" for w in who[:4]) or "— none"
            if len(who) > 4:
                who_s += f" +{len(who) - 4}"
            qual = route.get("qualifier") or "**$LATEST**"
            md.append(f"| `{esc(key)}` | {esc(qual)} | "
                      f"{esc(route.get('authorizationType') or '—')} | {who_s} |")
        md.append("")

    md.append("## Anomalies carried from the inventory")
    md.append("")
    md.append("Counts only. The inventory holds the detail and the justifications.")
    md.append("")
    md.append("| Anomaly | Count |")
    md.append("|---|--:|")
    for key, val in anomalies.items():
        n = len(val) if hasattr(val, "__len__") else val
        md.append(f"| `{key}` | {n} |")
    md.append("")

    OUT.write_text("\n".join(md) + "\n")
    print(f"wrote {OUT.relative_to(REPO)}  "
          f"({len(functions)} functions, {len(routes)} routes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
