#!/usr/bin/env node
/**
 * Writes docs/pages.md — every route in the build, with a localhost link for each.
 *
 * GENERATED FROM out/, NOT FROM src/pages. The two are not the same list: a file in
 * src/pages that is excluded from the export, or a dynamic route that produced no static
 * params, exists as source but has no page to open. Only the export says what actually
 * shipped, which is what a reviewer needs to click.
 *
 * Public vs internal comes from out/sitemap.xml, which scripts/generate-sitemap.js already
 * owns as the single authoritative allowlist - deriving it here rather than re-declaring it
 * keeps the two from drifting.
 *
 *   npm run build && node scripts/list-pages.js
 */
// ESM, matching scripts/generate-sitemap.js - package.json sets "type": "module", so
// require() throws here and __dirname does not exist.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname( fileURLToPath( import.meta.url ) );
const ROOT = path.join( __dirname, '..' );
const OUT = path.join( ROOT, 'out' );
const BASE = process.env.BASE || 'http://localhost:3000';

if ( !fs.existsSync( OUT ) ) {
  console.error( 'out/ is missing - run npm run build first' );
  process.exit( 1 );
}

const routes = [];
( function walk ( dir ) {
  for ( const entry of fs.readdirSync( dir, { withFileTypes: true } ) ) {
    const full = path.join( dir, entry.name );
    if ( entry.isDirectory() ) walk( full );
    else if ( entry.name === 'index.html' ) {
      const rel = path.relative( OUT, path.dirname( full ) ).split( path.sep ).join( '/' );
      routes.push( rel === '' ? '/' : `/${rel}/` );
    }
  }
}( OUT ) );
routes.sort();

const sitemap = path.join( OUT, 'sitemap.xml' );
const publicSet = new Set(
  fs.existsSync( sitemap )
    ? [ ...fs.readFileSync( sitemap, 'utf8' ).matchAll( /<loc>([^<]+)<\/loc>/g ) ]
      .map( m => m[ 1 ].replace( /^https?:\/\/[^/]+/, '' ) || '/' )
    : []
);

const pub = routes.filter( r => publicSet.has( r ) );
const internal = routes.filter( r => !publicSet.has( r ) );

// Group internal routes by first segment so 118 rows are navigable rather than a wall.
const groups = new Map();
for ( const r of internal ) {
  const key = r.split( '/' )[ 1 ] || '(root)';
  if ( !groups.has( key ) ) groups.set( key, [] );
  groups.get( key ).push( r );
}
const sortedGroups = [ ...groups.entries() ].sort( ( a, b ) => b[ 1 ].length - a[ 1 ].length || a[ 0 ].localeCompare( b[ 0 ] ) );

const L = [];
L.push( '# Pages' );
L.push( '' );
L.push( `Generated by \`scripts/list-pages.js\` from \`out/\`. Regenerate with \`npm run build && node scripts/list-pages.js\`.` );
L.push( '' );
L.push( `- **${routes.length}** pages in the export` );
L.push( `- **${pub.length}** public and indexable (in \`sitemap.xml\`)` );
L.push( `- **${internal.length}** internal — these require sign-in, and are excluded from the sitemap and from \`robots\` indexing` );
L.push( '' );
L.push( '## Running locally' );
L.push( '' );
L.push( '```bash' );
L.push( 'export NVM_DIR="$HOME/.nvm"; . "$NVM_DIR/nvm.sh"; nvm use 24' );
L.push( 'npm run dev     # then open the links below' );
L.push( '```' );
L.push( '' );
L.push( `Links point at \`${BASE}\`. Trailing slashes matter: \`trailingSlash\` is enabled, so \`/terms\` redirects and \`/terms/\` resolves.` );
L.push( '' );
L.push( `## Public pages (${pub.length})` );
L.push( '' );
L.push( 'These are the ones a visitor and a search engine can reach. Review these first.' );
L.push( '' );
L.push( '| # | Route | Open locally |' );
L.push( '| --- | --- | --- |' );
pub.forEach( ( r, i ) => L.push( `| ${i + 1} | \`${r}\` | [${BASE}${r}](${BASE}${r}) |` ) );
L.push( '' );
L.push( `## Internal pages (${internal.length})` );
L.push( '' );
L.push( 'Behind authentication. Listed so the set is reviewable, but none of these is public and none affects SEO.' );
L.push( '' );
for ( const [ key, list ] of sortedGroups ) {
  L.push( `### ${key} (${list.length})` );
  L.push( '' );
  L.push( '| Route | Open locally |' );
  L.push( '| --- | --- |' );
  list.forEach( r => L.push( `| \`${r}\` | [${BASE}${r}](${BASE}${r}) |` ) );
  L.push( '' );
}

const dest = path.join( ROOT, 'docs', 'pages.md' );
fs.mkdirSync( path.dirname( dest ), { recursive: true } );
fs.writeFileSync( dest, L.join( '\n' ) + '\n' );
console.log( `docs/pages.md written: ${routes.length} pages (${pub.length} public, ${internal.length} internal)` );
