#!/usr/bin/env python3
"""
FAQ Sync Script — Single Source of Truth

Reads shared/faq-config.json and generates:
  1. amplify/functions/shared/static_knowledge_base.py (Python backend)
  2. src/utils/faqSearch.ts (TypeScript frontend)

Usage: python scripts/sync_faq.py
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG_PATH = os.path.join(ROOT, 'shared', 'faq-config.json')
PY_OUTPUT = os.path.join(ROOT, 'amplify', 'functions', 'shared', 'static_knowledge_base.py')
TS_OUTPUT = os.path.join(ROOT, 'src', 'utils', 'faqSearch.ts')


def load_config():
    with open(CONFIG_PATH, 'r', encoding='utf-8') as f:
        return json.load(f)


def generate_python(config):
    brand = config['brand']
    faqs = config['faqs']
    categories = config.get('categories', {})
    default_response = config.get('defaultResponse', '')

    lines = [
        '"""',
        'Static Knowledge Base - Free Alternative to OpenSearch',
        '',
        'AUTO-GENERATED by scripts/sync_faq.py from shared/faq-config.json',
        'Do NOT edit manually — edit shared/faq-config.json and run: python scripts/sync_faq.py',
        '"""',
        '',
        f'BRAND_INFO = {json.dumps(brand, indent=4)}',
        '',
        'FAQ_DATABASE = [',
    ]
    for faq in faqs:
        entry = {
            'keywords': faq['keywords'],
            'question': faq['question'],
            'answer': faq['answer'],
        }
        lines.append(f'    {json.dumps(entry, ensure_ascii=False)},')
    lines.append(']')
    lines.append('')

    # Services info (static, not in JSON)
    lines.append("""SERVICES_INFO = {
    'whatsapp': {
        'name': 'WhatsApp Business API',
        'description': 'Professional WhatsApp messaging for businesses',
        'features': ['Automated responses', 'Bulk messaging', 'Rich media support', 'Analytics']
    },
    'sms': {
        'name': 'SMS Services',
        'description': 'Reliable SMS delivery across India',
        'features': ['Transactional SMS', 'Promotional SMS', 'OTP delivery', 'DLT compliant']
    },
    'voice': {
        'name': 'Voice Services',
        'description': 'Automated voice calls and IVR',
        'features': ['Text-to-speech', 'Call recording', 'IVR menus', 'Call analytics']
    },
    'ecommerce': {
        'name': 'E-commerce Solutions',
        'description': 'Complete online store management',
        'features': ['Product catalog', 'Payment gateway', 'Order management', 'Inventory tracking']
    }
}""")
    lines.append('')
    lines.append('')

    # Synonym map for improved matching
    lines.append("""# Synonym map for improved keyword matching (Fix #11)
SYNONYMS = {
    'pricing': 'price', 'prices': 'price', 'cost': 'cost', 'costs': 'cost',
    'payments': 'payment', 'paying': 'pay',
    'orders': 'order', 'ordering': 'order', 'ordered': 'order',
    'deliveries': 'delivery', 'delivered': 'delivery', 'delivering': 'delivery',
    'shipped': 'shipping', 'ships': 'shipping',
    'returns': 'return', 'returned': 'return', 'returning': 'return',
    'refunds': 'refund', 'refunded': 'refund',
    'cancels': 'cancel', 'cancelled': 'cancel', 'cancellation': 'cancel',
    'exchanges': 'exchange', 'exchanged': 'exchange',
    'tracking': 'track', 'tracked': 'track',
    'invoices': 'invoice', 'billing': 'bill', 'billed': 'bill',
    'accounts': 'account', 'logged': 'login', 'logging': 'login', 'signin': 'login', 'sign-in': 'login',
    'registered': 'register', 'registration': 'register', 'registering': 'register',
    'signed': 'signup', 'signing': 'signup',
    'called': 'call', 'calling': 'call',
    'emailed': 'email', 'emailing': 'email', 'emails': 'email',
    'helped': 'help', 'helping': 'help',
    'contacted': 'contact', 'contacting': 'contact',
    'purchased': 'purchase', 'purchasing': 'purchase', 'purchases': 'purchase',
    'shopping': 'shop', 'shopped': 'shop',
    'products': 'product',
    'charges': 'charge', 'charged': 'charge', 'charging': 'charge',
    'fees': 'fee',
    'discounts': 'discount', 'discounted': 'discount',
    'wholesale': 'bulk',
    'timings': 'timing', 'timetable': 'timing',
    'opened': 'open', 'opening': 'open',
    'closed': 'close', 'closing': 'close',
    'available': 'available', 'availability': 'available',
}""")
    lines.append('')
    lines.append('')

    # search function with synonym + stemming support + monitoring
    lines.append(f'DEFAULT_RESPONSE = {json.dumps(default_response)}')
    lines.append('')
    lines.append('')
    lines.append("""# Fix #9: FAQ search quality monitoring
import logging as _logging
_faq_logger = _logging.getLogger('faq_search')


def _normalize_query(query: str) -> str:
    \"\"\"Expand synonyms in query for better matching.\"\"\"
    words = query.lower().split()
    expanded = []
    for w in words:
        expanded.append(SYNONYMS.get(w, w))
    return ' '.join(expanded)


def search_knowledge_base(query: str, max_results: int = 3) -> str:
    \"\"\"
    Search the static knowledge base using keyword matching with synonym expansion.

    Args:
        query: User's question or search query
        max_results: Maximum number of results to return

    Returns:
        Formatted string with relevant answers
    \"\"\"
    query_normalized = _normalize_query(query)
    matches = []

    for faq in FAQ_DATABASE:
        score = sum(1 for kw in faq['keywords'] if kw in query_normalized)
        if score > 0:
            matches.append((score, faq))

    matches.sort(key=lambda x: x[0], reverse=True)
    top = matches[:max_results]

    if not top:
        _faq_logger.info(f"faq_no_match|query={query[:100]}|normalized={query_normalized[:100]}")
        return DEFAULT_RESPONSE

    matched_ids = [faq['question'][:40] for _, faq in top]
    _faq_logger.info(f"faq_match|query={query[:60]}|matches={len(top)}|top={matched_ids[0]}|score={top[0][0]}")

    results = []
    for score, faq in top:
        results.append(f"Q: {faq['question']}\\nA: {faq['answer']}")

    return '\\n\\n'.join(results)


def get_brand_info() -> dict:
    \"\"\"Get brand information.\"\"\"
    return BRAND_INFO


def get_service_info(service_name: str = None) -> dict:
    \"\"\"Get information about services.\"\"\"
    if service_name and service_name.lower() in SERVICES_INFO:
        return SERVICES_INFO[service_name.lower()]
    return SERVICES_INFO
""")

    with open(PY_OUTPUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    print(f'  ✓ Generated {PY_OUTPUT}')


def generate_typescript(config):
    brand = config['brand']
    faqs = config['faqs']
    categories = config.get('categories', {})
    default_response = config.get('defaultResponse', '')
    greetings = config.get('greetings', {})

    lines = [
        '/**',
        ' * FAQ Search Utility - Frontend',
        ' *',
        ' * AUTO-GENERATED by scripts/sync_faq.py from shared/faq-config.json',
        ' * Do NOT edit manually — edit shared/faq-config.json and run: python scripts/sync_faq.py',
        ' */',
        '',
        'export interface FAQ {',
        '  id: string;',
        '  keywords: string[];',
        '  category: string;',
        '  question: string;',
        '  answer: string;',
        '  shortAnswer: string;',
        '}',
        '',
        'export interface FAQSearchResult {',
        '  id: string;',
        '  question: string;',
        '  answer: string;',
        '  score: number;',
        '  category: string;',
        '  matchedKeywords: string[];',
        '}',
        '',
        'export interface BrandInfo {',
        '  name: string;',
        '  website: string;',
        '  store: string;',
        '  email: string;',
        '  phone: string;',
        '  whatsapp: string;',
        '}',
        '',
        '// FAQ Database — auto-generated from shared/faq-config.json',
        'const FAQ_DATABASE: FAQ[] = [',
    ]

    for faq in faqs:
        lines.append('  {')
        lines.append(f'    id: {json.dumps(faq["id"])},')
        lines.append(f'    keywords: {json.dumps(faq["keywords"])},')
        lines.append(f'    category: {json.dumps(faq["category"])},')
        lines.append(f'    question: {json.dumps(faq["question"])},')
        lines.append(f'    answer: {json.dumps(faq["answer"])},')
        lines.append(f'    shortAnswer: {json.dumps(faq.get("shortAnswer", ""))},')
        lines.append('  },')

    lines.append('];')
    lines.append('')

    # Brand info
    lines.append(f'const BRAND_INFO: BrandInfo = {{')
    lines.append(f'  name: {json.dumps(brand["name"])},')
    lines.append(f'  website: {json.dumps(brand["website"])},')
    lines.append(f'  store: {json.dumps(brand["store"])},')
    lines.append(f'  email: {json.dumps(brand["email"])},')
    lines.append(f'  phone: {json.dumps(brand["phone"])},')
    lines.append(f'  whatsapp: {json.dumps(brand["whatsapp"])},')
    lines.append('};')
    lines.append('')

    # Synonym map
    lines.append('// Synonym map for improved keyword matching')
    lines.append('const SYNONYMS: Record<string, string> = {')
    synonyms = {
        'pricing': 'price', 'prices': 'price', 'costs': 'cost',
        'payments': 'payment', 'paying': 'pay',
        'orders': 'order', 'ordering': 'order', 'ordered': 'order',
        'deliveries': 'delivery', 'delivered': 'delivery',
        'shipped': 'shipping', 'ships': 'shipping',
        'returns': 'return', 'returned': 'return',
        'refunds': 'refund', 'refunded': 'refund',
        'cancels': 'cancel', 'cancelled': 'cancel', 'cancellation': 'cancel',
        'exchanges': 'exchange',
        'tracking': 'track', 'tracked': 'track',
        'invoices': 'invoice', 'billing': 'bill',
        'accounts': 'account', 'logging': 'login', 'signin': 'login',
        'registered': 'register', 'registration': 'register',
        'called': 'call', 'calling': 'call',
        'emailed': 'email', 'emails': 'email',
        'helped': 'help', 'helping': 'help',
        'contacted': 'contact', 'contacting': 'contact',
        'purchased': 'purchase', 'purchases': 'purchase',
        'shopping': 'shop',
        'products': 'product',
        'charges': 'charge', 'charged': 'charge',
        'fees': 'fee',
        'discounts': 'discount',
        'wholesale': 'bulk',
        'timings': 'timing',
        'opened': 'open', 'closed': 'close',
    }
    for k, v in synonyms.items():
        lines.append(f'  {json.dumps(k)}: {json.dumps(v)},')
    lines.append('};')
    lines.append('')

    # Greetings
    greet_kw = json.dumps(greetings.get('keywords', ['hi', 'hello', 'hey', 'namaste']))
    greet_resp = json.dumps(greetings.get('response', 'Hi! 👋 Welcome to WECARE.DIGITAL.'))
    lines.append(f'const GREETINGS = {greet_kw};')
    lines.append(f'const DEFAULT_RESPONSE = {json.dumps(default_response)};')
    lines.append('')

    # Normalize function
    lines.append("""function normalizeQuery(query: string): string {
  return query.toLowerCase().split(/\\s+/).map(w => SYNONYMS[w] || w).join(' ');
}""")
    lines.append('')

    # searchFAQs
    lines.append("""/**
 * Search FAQs using keyword matching with synonym expansion
 */
export function searchFAQs(
  query: string,
  options: { maxResults?: number; shortAnswer?: boolean; category?: string } = {}
): FAQSearchResult[] {
  const { maxResults = 3, shortAnswer = false, category } = options;
  const queryNorm = normalizeQuery(query.trim());

  if (!queryNorm) return [];

  // Check for greetings
  if (GREETINGS.some(g => queryNorm.includes(g))) {
    return [{
      id: 'greeting', question: 'Greeting',
      answer: """ + greet_resp + """,
      score: 100, category: 'general', matchedKeywords: ['greeting']
    }];
  }

  const matches: FAQSearchResult[] = [];

  for (const faq of FAQ_DATABASE) {
    if (category && faq.category !== category) continue;
    let score = 0;
    const matchedKeywords: string[] = [];
    for (const keyword of faq.keywords) {
      if (queryNorm.includes(keyword.toLowerCase())) {
        score++;
        matchedKeywords.push(keyword);
      }
    }
    if (score > 0) {
      matches.push({
        id: faq.id, question: faq.question,
        answer: shortAnswer ? faq.shortAnswer : faq.answer,
        score, category: faq.category, matchedKeywords
      });
    }
  }

  return matches.sort((a, b) => b.score - a.score).slice(0, maxResults);
}""")
    lines.append('')

    # getAllFAQs
    lines.append("""/**
 * Get all FAQs grouped by category
 */
export function getAllFAQs(shortAnswer: boolean = false): Record<string, FAQ[]> {
  const grouped: Record<string, FAQ[]> = { general: [], orders: [], payments: [] };
  for (const faq of FAQ_DATABASE) {
    if (!grouped[faq.category]) grouped[faq.category] = [];
    grouped[faq.category].push(faq);
  }
  return grouped;
}""")
    lines.append('')

    # getFAQById
    lines.append("""/**
 * Get FAQ by ID
 */
export function getFAQById(id: string): FAQ | undefined {
  return FAQ_DATABASE.find(faq => faq.id === id);
}""")
    lines.append('')

    # getBrandInfo
    lines.append("""/**
 * Get brand information
 */
export function getBrandInfo(): BrandInfo {
  return BRAND_INFO;
}""")
    lines.append('')

    # formatSearchResponse
    lines.append("""/**
 * Get formatted response text from search results
 */
export function formatSearchResponse(results: FAQSearchResult[]): string {
  if (results.length === 0) return DEFAULT_RESPONSE;
  if (results.length === 1) return results[0].answer;
  return results.map(r => `Q: ${r.question}\\nA: ${r.answer}`).join('\\n\\n');
}""")
    lines.append('')

    # getCategoryName
    cat_json = json.dumps(categories)
    lines.append(f"""/**
 * Get category display name
 */
export function getCategoryName(category: string): string {{
  const names: Record<string, string> = {cat_json};
  return names[category] || category;
}}
""")

    with open(TS_OUTPUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    print(f'  ✓ Generated {TS_OUTPUT}')


def main():
    print('FAQ Sync: shared/faq-config.json → Python + TypeScript')
    config = load_config()
    print(f'  Loaded {len(config["faqs"])} FAQs, {len(config.get("categories", {}))} categories')
    generate_python(config)
    generate_typescript(config)
    print('  Done!')


if __name__ == '__main__':
    main()
